spring:
  application:
    name: ebean-sample
  datasource:
    url: jdbc:mariadb://127.0.0.1:3307/cloud
    username: root
    password: 123456
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      jdbc-url: jdbc:mariadb://127.0.0.1:3307/cloud
#      username: root
#      password: 123456
server:
  port: 8080
